name: Semver diff
description: Get the difference between two semantic versions
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  initial_release_type:
    description: 'Initial release type returned when there are no existing tags.'
    required: true
    default: 'patch'

outputs:
  release_type:
    description: 'The difference between two versions by the release type (MAJOR, MINOR, PATCH, PRERELEASE, BUILD)'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: copy
  color: white
