name: Semver diff
description: Get the difference between two semantic versions
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  initial_diff_part:
    description: 'Initial semver diff part returned when there are no existing tags.'
    required: true
    default: 'patch'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: copy
  color: white
